---
- name: Backup Switch Configurations
  hosts: all
  gather_facts: false
  connection: network_cli
  vars_files:
    - switch_vars.yml

  tasks:
    - name: Backup device configuration
      ios_config:
        backup: true
        backup_options:
          filename: "{{ inventory_hostname }}_{{ current_date }}"
          dir_path: /ansible_backups/cisco/{{ current_date }}
        diff_ignore_lines:
          - "^.*Time:"
          - "^.*Last configuration change"
          - "^.*NVRAM config last"

    - name: Cleanup configs
      shell: "sed -i {{ item }} {{ current_config }}"
      with_items: "{{ sed_commands }}"
      delegate_to: localhost

    - name: Check for Diffs
      shell: diff -B {{ current_config }} {{ yesterday_config }}
      failed_when: diff_result.rc > 1
      register: diff_result
      delegate_to: localhost

    - name: Make diff report files
      shell: vimdiff {{ yesterday_config }} {{ current_config }} -c TOhtml  -c 'w! /tmp/{{ inventory_hostname }}_{{ current_date }}.html' -c 'qa!'
      failed_when: "diff_output.rc > 1"
      delegate_to: localhost
      register: diff_output
      when: diff_result.rc != 0
      notify: email diffs
      async: 120
      poll: 30

  handlers:
    - name: email diffs
      mail:
        from: ansible@example.com
        to:
          - test@example.com
        subject: Diff report for {{ inventory_hostname }}
        subtype: html
        host: mailhub.cliffsnet.com
        attach: /tmp/{{ inventory_hostname }}_{{ current_date }}.html
      when: diff_result.rc != 0

    - name: remove temp files
      file:
        state: absent
        path: "/tmp/{{ inventory_hostname }}_{{ current_date }}.html"
      listen: email diffs