---
- name: Check for online hosts
  hosts: all
  gather_facts: false
  connection: network_cli
  vars_files:
    - cisco_vars.yml

  tasks:
    - name: Ping for reachability
      command: ping -c1 {{ inventory_hostname }}
      delegate_to: localhost
      register: ping_result
      ignore_errors: true

    - group_by: key=reachable
      when: ping_result.rc == 0

- name: Backup Switch Configurations
  hosts: reachable
  gather_facts: false
  connection: network_cli
  vars_files:
    - cisco_vars.yml

  tasks:
  - name: Backup device configuration
    ios_config:
      backup: true
      backup_options:
        filename: "{{ inventory_hostname }}_{{ current_date }}"
        dir_path: /ansible_backups/cisco/{{ current_date }}
      diff_ignore_lines:
        - "^.*Time:"
        - "^.*Last configuration change"
        - "^.*NVRAM config last"
    tags: backup

  - name: Check to see if {{ current_date }} directory exists
    stat:
      path: "{{ item }}"
    register: folder_check
    run_once: true
    with_items:
      - "{{ configs_dir }}"
      - "{{ diff_directory }}"
    delegate_to: localhost

  - name: Create {{ current_date }} folder when it does not exist
    file:
      path: "{{ item }}"
      state: directory
      mode: 0755
    run_once: true
    with_items:
      - "{{ configs_dir }}"
      - "{{ diff_directory }}"
    when: folder_check.stat.exists == false
    delegate_to: localhost

  - name: Cleanup configs
    shell: "sed -i {{ item }} {{ current_config }}"
    with_items: "{{ sed_commands }}"
    delegate_to: localhost
    tags: cleanup

  - name: Check if yesterday's configuration exists
    stat:
      path: "{{ yesterday_config }}"
    register: check_result
    delegate_to: localhost

  - name: Check for Diffs
    shell: diff -B {{ current_config }} {{ yesterday_config }}
    failed_when: diff_result.rc > 1
    register: diff_result
    when: check_result.stat.exists == true
    delegate_to: localhost
    tags: diffs

  - name: Make diff report files
    shell: vimdiff {{ yesterday_config }} {{ current_config }} -c TOhtml  -c 'w! /{{ diff_directory }}/{{ inventory_hostname }}_{{ current_date }}.html' -c 'qa!'
    failed_when: "diff_output.rc > 1"
    delegate_to: localhost
    register: diff_output
    when: diff_result.rc == 1
    notify: email diffs
    async: 120
    poll: 30
    tags: reports

  handlers:
    - name: email diffs
      mail:
        from: "{{ from_email }}"
        to: "{{ email_addresses }}"
        subject: Diff report for {{ inventory_hostname }}
        subtype: html
        host: "{{ smtp_server }}"
        attach: /{{ diff_directory }}/{{ inventory_hostname }}_{{ current_date }}.html
      when: diff_result.rc != 0

    # - name: remove temp files
    #   file:
    #     state: absent
    #     path: "/tmp/{{ inventory_hostname }}_{{ current_date }}.html"
    #   listen: email diffs